package Funciones_Principales;
import java.awt.Dimension;
public class VentanaPrincipal extends javax.swing.JFrame {
    public VentanaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setMinimumSize(new Dimension(600, 400));
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaCelular = new javax.swing.JLabel();
        etiquetaCorreo = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        textFieldNombre = new javax.swing.JTextField();
        textFieldCelular = new javax.swing.JTextField();
        textFieldCorreoElectronico = new javax.swing.JTextField();
        barraDeMenu = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuItemMostrarContactos = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDA DE CONTACTOS");

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        etiquetaNombre.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        panelPrincipal.add(etiquetaNombre, gridBagConstraints);

        etiquetaCelular.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaCelular.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCelular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCelular.setText("Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        panelPrincipal.add(etiquetaCelular, gridBagConstraints);

        etiquetaCorreo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaCorreo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCorreo.setText("Correo electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        panelPrincipal.add(etiquetaCorreo, gridBagConstraints);

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("AGENDA DE CONTACTOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 150);
        panelPrincipal.add(etiquetaTitulo, gridBagConstraints);

        botonAgregar.setBackground(new java.awt.Color(153, 153, 153));
        botonAgregar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonAgregar.setText("AGREGAR");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 150);
        panelPrincipal.add(botonAgregar, gridBagConstraints);

        textFieldNombre.setBackground(new java.awt.Color(102, 102, 102));
        textFieldNombre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        textFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        textFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 150);
        panelPrincipal.add(textFieldNombre, gridBagConstraints);

        textFieldCelular.setBackground(new java.awt.Color(102, 102, 102));
        textFieldCelular.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        textFieldCelular.setForeground(new java.awt.Color(255, 255, 255));
        textFieldCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 150);
        panelPrincipal.add(textFieldCelular, gridBagConstraints);

        textFieldCorreoElectronico.setBackground(new java.awt.Color(102, 102, 102));
        textFieldCorreoElectronico.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        textFieldCorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        textFieldCorreoElectronico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCorreoElectronico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 150);
        panelPrincipal.add(textFieldCorreoElectronico, gridBagConstraints);

        menu1.setBackground(new java.awt.Color(0, 0, 0));
        menu1.setText("Menu Principal");
        menu1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        menuItemMostrarContactos.setBackground(new java.awt.Color(0, 0, 0));
        menuItemMostrarContactos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuItemMostrarContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Contactos.png"))); // NOI18N
        menuItemMostrarContactos.setText("Mostrar Contactos");
        menuItemMostrarContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMostrarContactosActionPerformed(evt);
            }
        });
        menu1.add(menuItemMostrarContactos);
        menu1.add(separador1);

        menuItemSalir.setBackground(new java.awt.Color(0, 0, 0));
        menuItemSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Cerrar.png"))); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menu1.add(menuItemSalir);

        barraDeMenu.add(menu1);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void menuItemMostrarContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMostrarContactosActionPerformed
        VentanaContactos VC = new VentanaContactos(this, true);
        VC.setVisible(true);
    }//GEN-LAST:event_menuItemMostrarContactosActionPerformed
    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed
    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        ArchivoDeTexto archivo = new ArchivoDeTexto();                          //CLASE ARCHIVO
        archivo.crarArchivoDeContactos();                                       //CREA ARCHIVO
        String nombre = "", celular = "", correo = "";
        nombre = textFieldNombre.getText();                                     //GUARDA NOMBRE
        celular = textFieldCelular.getText();                                   //GUARDA CELULAR
        correo = textFieldCorreoElectronico.getText();                          //GUARDA CORREO
        Persona persona1 = new Persona(nombre, celular, correo);                //GUARDA DATOS PERSONA EN LA CLASE
        archivo.escribirTexto(persona1);                                        //ESCRIBIR DATOS PERSONA EN ARCHIVO
        //REINICIO DE LAS CAJAS DE TEXTO
        textFieldNombre.setText("");
        textFieldCelular.setText("");
        textFieldCorreoElectronico.setText("");
    }//GEN-LAST:event_botonAgregarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JLabel etiquetaCelular;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem menuItemMostrarContactos;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPopupMenu.Separator separador1;
    private javax.swing.JTextField textFieldCelular;
    private javax.swing.JTextField textFieldCorreoElectronico;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}