package Funciones_Principales;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
public class VentanaPrincipal extends javax.swing.JFrame {
    public VentanaPrincipal() {
        initComponents();
        this.setSize(700, 400);
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaTexto1 = new javax.swing.JLabel();
        etiquetaTexto2 = new javax.swing.JLabel();
        etiquetaTexto3 = new javax.swing.JLabel();
        etiquetaTexto4 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldEdad = new javax.swing.JTextField();
        textFieldPeso = new javax.swing.JTextField();
        textFieldEstatura = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        barraDeMenu = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuItemMostrarAtletasRegistrados = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE ATLETAS");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(102, 0, 102));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("REGISTRO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(etiquetaTitulo, gridBagConstraints);

        etiquetaTexto1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        etiquetaTexto1.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTexto1.setText("NOMBRE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(etiquetaTexto1, gridBagConstraints);

        etiquetaTexto2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        etiquetaTexto2.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTexto2.setText("EDAD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(etiquetaTexto2, gridBagConstraints);

        etiquetaTexto3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        etiquetaTexto3.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTexto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTexto3.setText("PESO [KG]:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(etiquetaTexto3, gridBagConstraints);

        etiquetaTexto4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        etiquetaTexto4.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTexto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTexto4.setText("ESTATURA [CM]:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(etiquetaTexto4, gridBagConstraints);

        textFieldNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 40);
        panelPrincipal.add(textFieldNombre, gridBagConstraints);

        textFieldEdad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 40);
        panelPrincipal.add(textFieldEdad, gridBagConstraints);

        textFieldPeso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 40);
        panelPrincipal.add(textFieldPeso, gridBagConstraints);

        textFieldEstatura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 40);
        panelPrincipal.add(textFieldEstatura, gridBagConstraints);

        botonRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        botonRegistrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("REGISTRAR ATLETA");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(botonRegistrar, gridBagConstraints);

        menu1.setForeground(new java.awt.Color(0, 0, 0));
        menu1.setText("Menu");
        menu1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        menu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menuItemMostrarAtletasRegistrados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menuItemMostrarAtletasRegistrados.setForeground(new java.awt.Color(0, 0, 0));
        menuItemMostrarAtletasRegistrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Atleta.png"))); // NOI18N
        menuItemMostrarAtletasRegistrados.setText("Mostrar Atletas Registrados");
        menuItemMostrarAtletasRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMostrarAtletasRegistradosActionPerformed(evt);
            }
        });
        menu1.add(menuItemMostrarAtletasRegistrados);
        menu1.add(separador1);

        menuItemSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menuItemSalir.setForeground(new java.awt.Color(0, 0, 0));
        menuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Cerrar.png"))); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menu1.add(menuItemSalir);

        barraDeMenu.add(menu1);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void menuItemMostrarAtletasRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMostrarAtletasRegistradosActionPerformed
        VentanaMostrarAtletas VMA = new VentanaMostrarAtletas(this, true);
        VMA.setVisible(true);
    }//GEN-LAST:event_menuItemMostrarAtletasRegistradosActionPerformed
    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed
    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String nombre;
        int edad;
        double peso;
        int estatura;
        nombre = textFieldNombre.getText();                                 //STRING
        edad = Integer.parseInt(textFieldEdad.getText());                   //ENTERO
        peso = Double.parseDouble(textFieldPeso.getText());                 //DOUBLE
        estatura = Integer.parseInt(textFieldEstatura.getText());           //ENTERO
        Atleta atleta = new Atleta(nombre, edad, peso, estatura);           //OBJETO
        escribirBinario(atleta);                                            //ESCRIBIMOS EN BINARIO
        limpiar();                                                          //LIMPIA TEXT FIELD'S
    }//GEN-LAST:event_botonRegistrarActionPerformed
    private void escribirBinario(Atleta atleta){
        try {
            //USANDO RUTA RELATIVA
            FileOutputStream archivo = new FileOutputStream("Registro Atletas.bin", true);
            AñadirBinario escribir = new AñadirBinario(archivo);
            escribir.writeObject(atleta);
            escribir.close();
            JOptionPane.showMessageDialog(null, "ATLETA REGISTRADO CORRECTAMENTE");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ERROR, EL ARCHIVO NO PUDO SER ENCONTRADO");
        } catch (IOException ex){
            JOptionPane.showMessageDialog(null, "ERROR, NO SE PUDO ESCRIBIR EN EL ARCHIVO");
        } 
    }
    private void limpiar(){
        textFieldNombre.setText("");
        textFieldEdad.setText("");
        textFieldPeso.setText("");
        textFieldEstatura.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JLabel etiquetaTexto1;
    private javax.swing.JLabel etiquetaTexto2;
    private javax.swing.JLabel etiquetaTexto3;
    private javax.swing.JLabel etiquetaTexto4;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem menuItemMostrarAtletasRegistrados;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPopupMenu.Separator separador1;
    private javax.swing.JTextField textFieldEdad;
    private javax.swing.JTextField textFieldEstatura;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldPeso;
    // End of variables declaration//GEN-END:variables
}