//MODIFICADORES DE ACCESO
package Paquete_1;
public class Clase_1 {
    //ATRIBUTOS
    public int Atributo_1 = 0;
    /*
        PUBLIC  -> SI SE COLOCA ESTÉ MODIFICADOR ENTONCES TODAS LAS CLASES, SEAN DEL PAQUETE O NO, TENDRAN ACCESO
        PRIVATE -> SI SE COLOCA ESTÉ MODIFICADOR ENCONCES SOLO LA PROPIA CLASE PUEDE TENER ACCESO
        SIN MODIFICADOR -> SI NO SE COLOCA NADA, SOLO SE PUEDE USAR POR TODAS LAS CLASES DEL MISMO PAQUETE
    */
}