package Vista;
import Modelo.Usuario;
import java.awt.Dimension;
public class Programa extends javax.swing.JFrame {
    Usuario usuario;
    public Programa() {
        //APLICAMOS SOBRECARGA DE CONSTRUCTORES POR ESO SOLO TENEMOS INIT COMPONENTS
        initComponents();
    }
    public Programa(Usuario usuario){
        initComponents();
        this.setSize(new Dimension(700, 500));
        this.setLocationRelativeTo(null);
        
        this.usuario = usuario;
        etiqueta1.setText(usuario.getNombre());
        etiqueta2.setText(usuario.getNombreRolDeUsuario());
        if(usuario.getIdTipoDeUsuario() == 1){
            //ADMINISTRADOR  
        }else if(usuario.getIdTipoDeUsuario() == 2){
            //USUARIO COMUN
            menuProveedores.setVisible(false);
            menuItemAgregarProducto.setVisible(false);
            menuItemModificarProducto.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        barraDeMenu1 = new javax.swing.JMenuBar();
        menuProductos = new javax.swing.JMenu();
        menuItemAgregarProducto = new javax.swing.JMenuItem();
        menuItemModificarProducto = new javax.swing.JMenuItem();
        menuItemCatalogoProductos = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        menuItemAgregarProveedor = new javax.swing.JMenuItem();
        menuItemCatalogoProveedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROGRAMA");

        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("BIENVENIDO AL PROGRAMA");

        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(etiqueta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiquetaTitulo)
                .addGap(18, 18, 18)
                .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        menuProductos.setText("Productos");

        menuItemAgregarProducto.setText("Agregar Producto");
        menuProductos.add(menuItemAgregarProducto);

        menuItemModificarProducto.setText("Modificar Producto");
        menuProductos.add(menuItemModificarProducto);

        menuItemCatalogoProductos.setText("Catalogo de Productos");
        menuProductos.add(menuItemCatalogoProductos);

        barraDeMenu1.add(menuProductos);

        menuProveedores.setText("Proveedores");

        menuItemAgregarProveedor.setText("Agregar Proveedor");
        menuProveedores.add(menuItemAgregarProveedor);

        menuItemCatalogoProveedores.setText("Catalogo de Proveedores");
        menuProveedores.add(menuItemCatalogoProveedores);

        barraDeMenu1.add(menuProveedores);

        setJMenuBar(barraDeMenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu1;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JMenuItem menuItemAgregarProducto;
    private javax.swing.JMenuItem menuItemAgregarProveedor;
    private javax.swing.JMenuItem menuItemCatalogoProductos;
    private javax.swing.JMenuItem menuItemCatalogoProveedores;
    private javax.swing.JMenuItem menuItemModificarProducto;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}