package Vista;
import Modelo.Cifrar_Contraseña;
import Modelo.SQL_Usuario;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;
public class Registro extends javax.swing.JFrame {
    public Registro() {
        initComponents();
        this.setSize(new Dimension(600, 370));
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        textoUsuario = new javax.swing.JLabel();
        textoContraseña = new javax.swing.JLabel();
        textoConfirmarContraseña = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoCorreoElectronico = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        passwordFieldContraseña = new javax.swing.JPasswordField();
        passwordFieldConfirmarContraseña = new javax.swing.JPasswordField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldCorreo = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR");
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        textoUsuario.setText("USUARIO:");

        textoContraseña.setText("CONTRASEÑA:");

        textoConfirmarContraseña.setText("CONFIRMAR CONTRASEÑA:");

        textoNombre.setText("NOMBRE:");

        textoCorreoElectronico.setText("CORREO:");

        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoConfirmarContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textoCorreoElectronico)
                                .addComponent(textoNombre)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNombre)
                            .addComponent(textFieldUsuario)
                            .addComponent(textFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(passwordFieldContraseña)
                            .addComponent(passwordFieldConfirmarContraseña)))
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoUsuario)
                    .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoContraseña)
                    .addComponent(passwordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConfirmarContraseña)
                    .addComponent(passwordFieldConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCorreoElectronico)
                    .addComponent(textFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonRegistrar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        Usuario usuario = new Usuario();
        SQL_Usuario sql_usuario = new SQL_Usuario();
        String contraseña = new String(passwordFieldContraseña.getPassword());
        String confirmarContraseña = new String(passwordFieldConfirmarContraseña.getPassword());
        if (    (textFieldUsuario.getText().isEmpty())||
                    (contraseña.isEmpty())||
                        (confirmarContraseña.isEmpty())||
                            (textFieldNombre.getText().isEmpty())||
                                (textFieldCorreo.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "FALTAN CAMPOS POR RELLENAR");
        }else{
            if(contraseña.equals(confirmarContraseña)){
                if(sql_usuario.verificarUsuario(textFieldUsuario.getText())==0){
                    if(sql_usuario.comprobarFormatoEmail(textFieldCorreo.getText())){
                        //CIFRAMOS LA CONTRASEÑA
                        String contraseñaCifradaMD5 = Cifrar_Contraseña.md5(contraseña);
                        //GUARDANDO DATOS EN MySQL
                        usuario.setNombreUsuario(textFieldUsuario.getText());
                        usuario.setContraseña(contraseñaCifradaMD5);
                        usuario.setNombre(textFieldNombre.getText());
                        usuario.setCorreo(textFieldCorreo.getText());
                        //1 = ADMINISTRADOR ;;;; 2 = USUARIO
                        usuario.setIdTipoDeUsuario(1);                          //CAMBIO MANUAL
                        if (sql_usuario.registrar(usuario)) {
                            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
                            limpiarCampos();
                        } else {
                            JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "INGRESE UN CORREO VALIDO");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "YA EXISTE UN USUARIO CON ESTE NOMBRE");
                }
            }else{
                JOptionPane.showMessageDialog(null, "LAS CONTRASEÑAS NO COINCIDEN");
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Inicio.registrar = null;
    }//GEN-LAST:event_formWindowClosing
    public void limpiarCampos(){
        textFieldUsuario.setText("");
        passwordFieldContraseña.setText("");
        passwordFieldConfirmarContraseña.setText("");
        textFieldNombre.setText("");
        textFieldCorreo.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField passwordFieldConfirmarContraseña;
    private javax.swing.JPasswordField passwordFieldContraseña;
    private javax.swing.JTextField textFieldCorreo;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldUsuario;
    private javax.swing.JLabel textoConfirmarContraseña;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JLabel textoCorreoElectronico;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoUsuario;
    // End of variables declaration//GEN-END:variables
}