package Funciones_Principales;
public class Ventana extends javax.swing.JFrame {
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        poster1 = new javax.swing.JLabel();
        etiquetaTituloPoster1 = new javax.swing.JLabel();
        etiquetaGeneroPoster1 = new javax.swing.JLabel();
        poster2 = new javax.swing.JLabel();
        etiquetaTituloPoster2 = new javax.swing.JLabel();
        etiquetaGeneroPoster2 = new javax.swing.JLabel();
        poster3 = new javax.swing.JLabel();
        etiquetaTituloPoster3 = new javax.swing.JLabel();
        etiquetaGeneroPoster3 = new javax.swing.JLabel();
        poster4 = new javax.swing.JLabel();
        etiquetaTituloPoster4 = new javax.swing.JLabel();
        etiquetaGeneroPoster4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cartelera Cinépolis");
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        poster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TB_Poster1.png"))); // NOI18N
        poster1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(poster1, gridBagConstraints);

        etiquetaTituloPoster1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaTituloPoster1.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTituloPoster1.setText("TITULO: THE BATMAN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(etiquetaTituloPoster1, gridBagConstraints);

        etiquetaGeneroPoster1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        etiquetaGeneroPoster1.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaGeneroPoster1.setText("GENERO: DRAMA / FICCION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(etiquetaGeneroPoster1, gridBagConstraints);

        poster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JK_Poster2.png"))); // NOI18N
        poster2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(poster2, gridBagConstraints);

        etiquetaTituloPoster2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaTituloPoster2.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTituloPoster2.setText("TITULO: JOKER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(etiquetaTituloPoster2, gridBagConstraints);

        etiquetaGeneroPoster2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        etiquetaGeneroPoster2.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaGeneroPoster2.setText("GENERO: DRAMA / COMEDIA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(etiquetaGeneroPoster2, gridBagConstraints);

        poster3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ELC_Poster3.jpg"))); // NOI18N
        poster3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(poster3, gridBagConstraints);

        etiquetaTituloPoster3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaTituloPoster3.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTituloPoster3.setText("TITULO: EL CAMINO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(etiquetaTituloPoster3, gridBagConstraints);

        etiquetaGeneroPoster3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        etiquetaGeneroPoster3.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaGeneroPoster3.setText("GENERO: DRAMA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(etiquetaGeneroPoster3, gridBagConstraints);

        poster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AV_Poster4.jpg"))); // NOI18N
        poster4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        jPanel1.add(poster4, gridBagConstraints);

        etiquetaTituloPoster4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        etiquetaTituloPoster4.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTituloPoster4.setText("TITULO: AVATAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(etiquetaTituloPoster4, gridBagConstraints);

        etiquetaGeneroPoster4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        etiquetaGeneroPoster4.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaGeneroPoster4.setText("GENERO: DRAMA / FICCION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(etiquetaGeneroPoster4, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaGeneroPoster1;
    private javax.swing.JLabel etiquetaGeneroPoster2;
    private javax.swing.JLabel etiquetaGeneroPoster3;
    private javax.swing.JLabel etiquetaGeneroPoster4;
    private javax.swing.JLabel etiquetaTituloPoster1;
    private javax.swing.JLabel etiquetaTituloPoster2;
    private javax.swing.JLabel etiquetaTituloPoster3;
    private javax.swing.JLabel etiquetaTituloPoster4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel poster1;
    private javax.swing.JLabel poster2;
    private javax.swing.JLabel poster3;
    private javax.swing.JLabel poster4;
    // End of variables declaration//GEN-END:variables
}
