package Funciones_Principales;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
public class Ventana_ConvertidorDivisas extends javax.swing.JFrame {
    private String divisa1 = "";
    private String divisa2 = "";
    private String cantidad = "";
    private double cantidadTotalDeDinero = 0, cambio = 0;
    private boolean punto = true;
    public Ventana_ConvertidorDivisas() {
        initComponents();
        this.setSize(280, 430);
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelDivisas = new javax.swing.JPanel();
        etiquetaDivisa1 = new javax.swing.JLabel();
        etiquetaDivisa2 = new javax.swing.JLabel();
        etiquetaCambio1 = new javax.swing.JLabel();
        etiquetaCambio2 = new javax.swing.JLabel();
        comboBoxDivisas1 = new javax.swing.JComboBox<>();
        comboBoxDivisas2 = new javax.swing.JComboBox<>();
        botonC = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonNumero9 = new javax.swing.JButton();
        botonNumero8 = new javax.swing.JButton();
        botonNumero7 = new javax.swing.JButton();
        botonNumero6 = new javax.swing.JButton();
        botonNumero5 = new javax.swing.JButton();
        botonNumero4 = new javax.swing.JButton();
        botonNumero3 = new javax.swing.JButton();
        botonNumero2 = new javax.swing.JButton();
        botonNumero1 = new javax.swing.JButton();
        botonNumero0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuCalculadoraEstandar = new javax.swing.JMenuItem();
        menuConversorDivisas = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor Divisas");
        setResizable(false);

        panelDivisas.setLayout(new java.awt.GridBagLayout());

        etiquetaDivisa1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        etiquetaDivisa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDivisa1.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        panelDivisas.add(etiquetaDivisa1, gridBagConstraints);

        etiquetaDivisa2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        etiquetaDivisa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDivisa2.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        panelDivisas.add(etiquetaDivisa2, gridBagConstraints);

        etiquetaCambio1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        etiquetaCambio1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelDivisas.add(etiquetaCambio1, gridBagConstraints);

        etiquetaCambio2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        etiquetaCambio2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelDivisas.add(etiquetaCambio2, gridBagConstraints);

        comboBoxDivisas1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        comboBoxDivisas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos - Dolar", "Peru - Sol", "Europa - Euro" }));
        comboBoxDivisas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDivisas1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelDivisas.add(comboBoxDivisas1, gridBagConstraints);

        comboBoxDivisas2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        comboBoxDivisas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos - Dolar", "Peru - Sol", "Europa - Euro" }));
        comboBoxDivisas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDivisas2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelDivisas.add(comboBoxDivisas2, gridBagConstraints);

        botonC.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelDivisas.add(botonC, gridBagConstraints);

        botonBorrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoBorrar.png"))); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelDivisas.add(botonBorrar, gridBagConstraints);

        botonNumero9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero9.setText("9");
        botonNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero9, gridBagConstraints);

        botonNumero8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero8.setText("8");
        botonNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero8, gridBagConstraints);

        botonNumero7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero7.setText("7");
        botonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero7, gridBagConstraints);

        botonNumero6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero6.setText("6");
        botonNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero6, gridBagConstraints);

        botonNumero5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero5.setText("5");
        botonNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero5, gridBagConstraints);

        botonNumero4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero4.setText("4");
        botonNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero4, gridBagConstraints);

        botonNumero3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero3.setText("3");
        botonNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero3, gridBagConstraints);

        botonNumero2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero2.setText("2");
        botonNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero2, gridBagConstraints);

        botonNumero1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero1.setText("1");
        botonNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero1, gridBagConstraints);

        botonNumero0.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonNumero0.setText("0");
        botonNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonNumero0, gridBagConstraints);

        botonPunto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelDivisas.add(botonPunto, gridBagConstraints);

        menu1.setText("Usos");
        menu1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        menuCalculadoraEstandar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuCalculadoraEstandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Calculadora.png"))); // NOI18N
        menuCalculadoraEstandar.setText("Calculadora Estándar");
        menuCalculadoraEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalculadoraEstandarActionPerformed(evt);
            }
        });
        menu1.add(menuCalculadoraEstandar);

        menuConversorDivisas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuConversorDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Divisas.png"))); // NOI18N
        menuConversorDivisas.setText("Conversor de Divisas");
        menuConversorDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConversorDivisasActionPerformed(evt);
            }
        });
        menu1.add(menuConversorDivisas);
        menu1.add(separador1);

        menuSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoCerrar.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menu1.add(menuSalir);

        menuPrincipal.add(menu1);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDivisas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDivisas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void menuConversorDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConversorDivisasActionPerformed
        //VACIO
    }//GEN-LAST:event_menuConversorDivisasActionPerformed
    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed
    private void menuCalculadoraEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalculadoraEstandarActionPerformed
        Ventana_CalculadoraEstandar estandar = new Ventana_CalculadoraEstandar();
        estandar.setVisible(true);
        dispose();                                                              //CERRANDO VENTANA ACTUAL
    }//GEN-LAST:event_menuCalculadoraEstandarActionPerformed
    private void botonNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero3ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "3";
        }else{
            cantidad += "3";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero3ActionPerformed
    private void comboBoxDivisas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDivisas1ActionPerformed
        divisa1 = (String) comboBoxDivisas1.getSelectedItem();                  //GUARDAMOS LA OPCIÓN
        if(divisa1.equals("Estados Unidos - Dolar")){
            etiquetaDivisa1.setText("$");
            obtenerDinero();
        }else if(divisa1.equals("Peru - Sol")){
            etiquetaDivisa1.setText("S/.");
        }else if(divisa1.equals("Europa - Euro")){
            etiquetaDivisa1.setText("€");
        }
        obtenerDinero();
    }//GEN-LAST:event_comboBoxDivisas1ActionPerformed
    private void comboBoxDivisas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDivisas2ActionPerformed
        divisa2 = (String) comboBoxDivisas2.getSelectedItem();                  //GUARDAMOS LA OPCIÓN
        if(divisa2.equals("Estados Unidos - Dolar")){
            etiquetaDivisa2.setText("$");
            obtenerDinero();
        }else if(divisa2.equals("Peru - Sol")){
            etiquetaDivisa2.setText("S/.");
        }else if(divisa2.equals("Europa - Euro")){
            etiquetaDivisa2.setText("€");
        }
        obtenerDinero();
    }//GEN-LAST:event_comboBoxDivisas2ActionPerformed
    private void botonNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero1ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "1";
        }else{
            cantidad += "1";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero1ActionPerformed

    private void botonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero2ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "2";
        }else{
            cantidad += "2";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero2ActionPerformed
    private void botonNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero4ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "4";
        }else{
            cantidad += "4";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero4ActionPerformed
    private void botonNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero5ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "5";
        }else{
            cantidad += "5";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero5ActionPerformed
    private void botonNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero6ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "6";
        }else{
            cantidad += "6";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero6ActionPerformed
    private void botonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero7ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "7";
        }else{
            cantidad += "7";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero7ActionPerformed
    private void botonNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero8ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "8";
        }else{
            cantidad += "8";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero8ActionPerformed
    private void botonNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero9ActionPerformed
        if(etiquetaCambio1.getText() == "0"){
            cantidad = "9";
        }else{
            cantidad += "9";
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_botonNumero9ActionPerformed

    private void botonNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero0ActionPerformed
        if(cantidad != ""){
            if (etiquetaCambio1.getText() == "0") {
                cantidad = "0";
            } else {
                cantidad += "0";
            }
            etiquetaCambio1.setText(cantidad);
            obtenerDinero();
        }
    }//GEN-LAST:event_botonNumero0ActionPerformed
    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if (punto == true) {
            if (cantidad == "") {
                cantidad = "0.";
            } else {
                cantidad += ".";
            }
            etiquetaCambio1.setText(cantidad);
            punto = false;
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int tamaño = cantidad.length();
        if(tamaño > 0){
            if(tamaño == 1){
                cantidad = "0";
            }else{
                cantidad = cantidad.substring(0,cantidad.length()-1);                 //BORRANDO DESDE LA DERECHA
            }
            etiquetaCambio1.setText(cantidad);
            obtenerDinero();
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        cantidad = "";
        punto = true;
        etiquetaCambio1.setText("0");
        etiquetaCambio2.setText("0");
    }//GEN-LAST:event_botonCActionPerformed
    private void obtenerDinero(){
        cantidad = etiquetaCambio1.getText();
        cantidadTotalDeDinero = Double.parseDouble(cantidad);
        cambioDeDivisas();
        cantidadTotalDeDinero *= cambio;
        etiquetaCambio2.setText(String.format("%.2f", cantidadTotalDeDinero));  //REDONDEADO A 2 DECIMALES
    }
    private void cambioDeDivisas(){
        if(divisa1.equals(divisa2)){
            //MISMA MONEDA A MISMA MONEDA
            cambio = 1;
        }else if(divisa1.equals("Estados Unidos - Dolar") && divisa2.equals("Peru - Sol")){
            //DOLAR A SOL
            cambio = 3.25;
        }else if(divisa1.equals("Estados Unidos - Dolar") && divisa2.equals("Europa - Euro")){
            //DOLAR A EURO
            cambio = 0.84;
        }else if(divisa1.equals("Peru - Sol") && divisa2.equals("Estados Unidos - Dolar")){
            //SOL A DOLAR
            cambio = 0.32;
        }else if(divisa1.equals("Peru - Sol") && divisa2.equals("Europa - Euro")){
            //SOL A EURO
            cambio = 0.26;
        }else if(divisa1.equals("Europa - Euro") && divisa2.equals("Estados Unidos - Dolar")){
            //EURO A DOLAR
            cambio = 1.2;
        }else if(divisa1.equals("Europa - Euro") && divisa2.equals("Peru - Sol")){
            //EURO A SOL
            cambio = 3.91;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Ventana_ConvertidorDivisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_ConvertidorDivisas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonNumero0;
    private javax.swing.JButton botonNumero1;
    private javax.swing.JButton botonNumero2;
    private javax.swing.JButton botonNumero3;
    private javax.swing.JButton botonNumero4;
    private javax.swing.JButton botonNumero5;
    private javax.swing.JButton botonNumero6;
    private javax.swing.JButton botonNumero7;
    private javax.swing.JButton botonNumero8;
    private javax.swing.JButton botonNumero9;
    private javax.swing.JButton botonPunto;
    private javax.swing.JComboBox<String> comboBoxDivisas1;
    private javax.swing.JComboBox<String> comboBoxDivisas2;
    private javax.swing.JLabel etiquetaCambio1;
    private javax.swing.JLabel etiquetaCambio2;
    private javax.swing.JLabel etiquetaDivisa1;
    private javax.swing.JLabel etiquetaDivisa2;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem menuCalculadoraEstandar;
    private javax.swing.JMenuItem menuConversorDivisas;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelDivisas;
    private javax.swing.JPopupMenu.Separator separador1;
    // End of variables declaration//GEN-END:variables
}
