package Funciones_Principales;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
public class Ventana_CalculadoraEstandar extends javax.swing.JFrame {
    private String cadenaDeNumeros = "";
    private double numero1 = 0, numero2 = 0, resultado = 0;
    private String operacion = "null";
    private boolean activacion = true, accionPunto = true;
    public Ventana_CalculadoraEstandar() {
        initComponents();
        this.setSize(280, 430);
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCalculadora = new javax.swing.JPanel();
        etiquetaMuestra = new javax.swing.JLabel();
        etiquetaNumeros = new javax.swing.JLabel();
        botonReiniciar = new javax.swing.JButton();
        botonRaizCuadrada = new javax.swing.JToggleButton();
        botonDividir = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonNumero7 = new javax.swing.JButton();
        botonNumero8 = new javax.swing.JButton();
        botonNumero9 = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        botonNumero4 = new javax.swing.JButton();
        botonNumero5 = new javax.swing.JButton();
        botonNumero6 = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        botonNumero1 = new javax.swing.JButton();
        botonNumero2 = new javax.swing.JButton();
        botonNumero3 = new javax.swing.JButton();
        botonSumar = new javax.swing.JButton();
        botonCambiarSigno = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonPuntoDecimal = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuCalculadoraEstandar = new javax.swing.JMenuItem();
        menuConversorDivisas = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Estándar");
        setResizable(false);

        panelCalculadora.setLayout(new java.awt.GridBagLayout());

        etiquetaMuestra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 10);
        panelCalculadora.add(etiquetaMuestra, gridBagConstraints);

        etiquetaNumeros.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNumeros.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCalculadora.add(etiquetaNumeros, gridBagConstraints);

        botonReiniciar.setBackground(new java.awt.Color(153, 153, 153));
        botonReiniciar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        botonReiniciar.setForeground(new java.awt.Color(0, 0, 0));
        botonReiniciar.setText("C");
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonReiniciar, gridBagConstraints);

        botonRaizCuadrada.setBackground(new java.awt.Color(153, 153, 153));
        botonRaizCuadrada.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonRaizCuadrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRaizCuadrada.png"))); // NOI18N
        botonRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizCuadradaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonRaizCuadrada, gridBagConstraints);

        botonDividir.setBackground(new java.awt.Color(153, 153, 153));
        botonDividir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoDivision.png"))); // NOI18N
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonDividir, gridBagConstraints);

        botonBorrar.setBackground(new java.awt.Color(153, 153, 153));
        botonBorrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoBorrar.png"))); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonBorrar, gridBagConstraints);

        botonNumero7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero7.setText("7");
        botonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero7, gridBagConstraints);

        botonNumero8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero8.setText("8");
        botonNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero8, gridBagConstraints);

        botonNumero9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero9.setText("9");
        botonNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero9, gridBagConstraints);

        botonMultiplicar.setBackground(new java.awt.Color(153, 153, 153));
        botonMultiplicar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        botonMultiplicar.setText("X");
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonMultiplicar, gridBagConstraints);

        botonNumero4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero4.setText("4");
        botonNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero4, gridBagConstraints);

        botonNumero5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero5.setText("5");
        botonNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero5, gridBagConstraints);

        botonNumero6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero6.setText("6");
        botonNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero6, gridBagConstraints);

        botonRestar.setBackground(new java.awt.Color(153, 153, 153));
        botonRestar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonRestar.setForeground(new java.awt.Color(0, 0, 0));
        botonRestar.setText("-");
        botonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonRestar, gridBagConstraints);

        botonNumero1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero1.setText("1");
        botonNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero1, gridBagConstraints);

        botonNumero2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero2.setText("2");
        botonNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero2, gridBagConstraints);

        botonNumero3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonNumero3.setText("3");
        botonNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonNumero3, gridBagConstraints);

        botonSumar.setBackground(new java.awt.Color(153, 153, 153));
        botonSumar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonSumar.setForeground(new java.awt.Color(0, 0, 0));
        botonSumar.setText("+");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonSumar, gridBagConstraints);

        botonCambiarSigno.setBackground(new java.awt.Color(153, 153, 153));
        botonCambiarSigno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoMasMenos.png"))); // NOI18N
        botonCambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarSignoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonCambiarSigno, gridBagConstraints);

        botonCero.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonCero, gridBagConstraints);

        botonPuntoDecimal.setBackground(new java.awt.Color(153, 153, 153));
        botonPuntoDecimal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonPuntoDecimal.setForeground(new java.awt.Color(0, 0, 0));
        botonPuntoDecimal.setText(".");
        botonPuntoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoDecimalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonPuntoDecimal, gridBagConstraints);

        botonIgual.setBackground(new java.awt.Color(153, 153, 153));
        botonIgual.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonIgual.setForeground(new java.awt.Color(0, 0, 0));
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelCalculadora.add(botonIgual, gridBagConstraints);

        menu1.setText("Usos");
        menu1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        menuCalculadoraEstandar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuCalculadoraEstandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Calculadora.png"))); // NOI18N
        menuCalculadoraEstandar.setText("Calculadora Estándar");
        menu1.add(menuCalculadoraEstandar);

        menuConversorDivisas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuConversorDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Divisas.png"))); // NOI18N
        menuConversorDivisas.setText("Conversor de Divisas");
        menuConversorDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConversorDivisasActionPerformed(evt);
            }
        });
        menu1.add(menuConversorDivisas);
        menu1.add(separador1);

        menuSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoCerrar.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menu1.add(menuSalir);

        menuPrincipal.add(menu1);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void menuConversorDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConversorDivisasActionPerformed
        Ventana_ConvertidorDivisas convertidor = new Ventana_ConvertidorDivisas();
        convertidor.setVisible(true);
        dispose();                                                              //CERRANDO VENTANA ACTUAL
    }//GEN-LAST:event_menuConversorDivisasActionPerformed
    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed
    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        if(activacion == true){
            numero1 = Double.parseDouble(cadenaDeNumeros);
            etiquetaMuestra.setText(cadenaDeNumeros+" / ");
            cadenaDeNumeros = "";                                               //VACIAMOS LA CADENA
            operacion = "DIVIDIR";
            activacion = false;                                                 //DESACTIVACION DEL BOTON
            accionPunto = true;
        } 
    }//GEN-LAST:event_botonDividirActionPerformed
    private void botonNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero8ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "8";
        }else{
            cadenaDeNumeros += "8";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero8ActionPerformed
    private void botonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero7ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "7";
        }else{
            cadenaDeNumeros += "7";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero7ActionPerformed
    private void botonNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero1ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "1";
        }else{
            cadenaDeNumeros += "1";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero1ActionPerformed
    private void botonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero2ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "2";
        }else{
            cadenaDeNumeros += "2";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero2ActionPerformed
    private void botonNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero3ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "3";
        }else{
            cadenaDeNumeros += "3";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero3ActionPerformed
    private void botonNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero4ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "4";
        }else{
            cadenaDeNumeros += "4";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero4ActionPerformed
    private void botonNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero5ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "5";
        }else{
            cadenaDeNumeros += "5";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero5ActionPerformed
    private void botonNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero6ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "6";
        }else{
            cadenaDeNumeros += "6";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero6ActionPerformed
    private void botonNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero9ActionPerformed
        if(etiquetaNumeros.getText()=="0"){
            cadenaDeNumeros = "9";
        }else{
            cadenaDeNumeros += "9";
        }        
        etiquetaNumeros.setText(cadenaDeNumeros);
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonNumero9ActionPerformed
    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
        if(cadenaDeNumeros != ""){
            if(etiquetaNumeros.getText()=="0"){
                cadenaDeNumeros = "0";
            }else{
                cadenaDeNumeros += "0";
            }        
            etiquetaNumeros.setText(cadenaDeNumeros);
            activacion = true;                                                      //ACTIVACION DEL BOTON
        }
    }//GEN-LAST:event_botonCeroActionPerformed
    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        if(activacion == true){
            numero1 = Double.parseDouble(cadenaDeNumeros);
            etiquetaMuestra.setText(cadenaDeNumeros+" + ");
            cadenaDeNumeros = "";                                               //VACIAMOS LA CADENA
            operacion = "SUMAR";
            activacion = false;                                                 //DESACTIVACION DEL BOTON
            accionPunto = true;
        }        
    }//GEN-LAST:event_botonSumarActionPerformed
    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        if(operacion.equals("null")){
            etiquetaNumeros.setText(cadenaDeNumeros);
        }else if(operacion.equals("SUMAR")){
            numero2 = Double.parseDouble(cadenaDeNumeros);
            resultado = numero1 + numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));          //RESULTADO SUMA CON 2 DECIMALES
            cadenaDeNumeros = String.valueOf(resultado);                        //GUARDAMOS EL RESULTADO
            operacion = "nula";
        }else if(operacion.equals("RESTAR")){
            numero2 = Double.parseDouble(cadenaDeNumeros);
            resultado = numero1 - numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));          //RESULTADO RESTA CON 2 DECIMALES
            cadenaDeNumeros = String.valueOf(resultado);                        //GUARDAMOS EL RESULTADO
            operacion = "nula";
        }else if(operacion.equals("MULTIPLICAR")){
            numero2 = Double.parseDouble(cadenaDeNumeros);
            resultado = numero1 * numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));          //RESULTADO MULTIPLICAR CON 2 DECIMALES
            cadenaDeNumeros = String.valueOf(resultado);                        //GUARDAMOS EL RESULTADO
            operacion = "nula";
        }else if(operacion.equals("DIVIDIR")){
            numero2 = Double.parseDouble(cadenaDeNumeros);
            resultado = numero1 / numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));          //RESULTADO DIVIDIR CON 2 DECIMALES
            cadenaDeNumeros = String.valueOf(resultado);                        //GUARDAMOS EL RESULTADO
            operacion = "nula";
        }
        etiquetaMuestra.setText("");
        activacion = true;                                                      //ACTIVACION DEL BOTON
    }//GEN-LAST:event_botonIgualActionPerformed
    private void botonPuntoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoDecimalActionPerformed
        if(accionPunto == true){
            if(cadenaDeNumeros == ""){
                cadenaDeNumeros += "0.";
            }else{
                cadenaDeNumeros += ".";
            }
            etiquetaNumeros.setText(cadenaDeNumeros);
            accionPunto = false;
        }
    }//GEN-LAST:event_botonPuntoDecimalActionPerformed
    private void botonCambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarSignoActionPerformed
        if(cadenaDeNumeros.charAt(0) != '-'){
            cadenaDeNumeros = "-"+cadenaDeNumeros;
        }else{
            cadenaDeNumeros = cadenaDeNumeros.substring(1,cadenaDeNumeros.length());    //CORTAMOS CADENA
        }
        etiquetaNumeros.setText(cadenaDeNumeros);
    }//GEN-LAST:event_botonCambiarSignoActionPerformed
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int tamaño = cadenaDeNumeros.length();
        if(tamaño > 0){
            if(tamaño == 1){
                cadenaDeNumeros = "0";
            }else{
                cadenaDeNumeros = cadenaDeNumeros.substring(0, cadenaDeNumeros.length()-1);
            }            
            etiquetaNumeros.setText(cadenaDeNumeros);
        }        
    }//GEN-LAST:event_botonBorrarActionPerformed
    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestarActionPerformed
        if(activacion == true){
            numero1 = Double.parseDouble(cadenaDeNumeros);
            etiquetaMuestra.setText(cadenaDeNumeros+" - ");
            cadenaDeNumeros = "";                                               //VACIAMOS LA CADENA
            operacion = "RESTAR";
            activacion = false;                                                 //DESACTIVACION DEL BOTON
            accionPunto = true;
        }  
    }//GEN-LAST:event_botonRestarActionPerformed
    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        if(activacion == true){
            numero1 = Double.parseDouble(cadenaDeNumeros);
            etiquetaMuestra.setText(cadenaDeNumeros+" * ");
            cadenaDeNumeros = "";                                               //VACIAMOS LA CADENA
            operacion = "MULTIPLICAR";
            activacion = false;                                                 //DESACTIVACION DEL BOTON
            accionPunto = true;
        }  
    }//GEN-LAST:event_botonMultiplicarActionPerformed
    private void botonRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizCuadradaActionPerformed
        numero1 = Double.parseDouble(cadenaDeNumeros);
        etiquetaMuestra.setText("sqrt("+cadenaDeNumeros+")");
        resultado = Math.sqrt(numero1);
        etiquetaNumeros.setText(String.format("%.2f", resultado));          //RESULTADO RAIZ CON 2 DECIMALES
        cadenaDeNumeros = String.valueOf(resultado);                        //GUARDAMOS EL RESULTADO
        accionPunto = true;       
    }//GEN-LAST:event_botonRaizCuadradaActionPerformed
    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        etiquetaMuestra.setText("");
        etiquetaNumeros.setText("0");
        cadenaDeNumeros = "";
        operacion = "nula";
        activacion = true;
        accionPunto = true;
    }//GEN-LAST:event_botonReiniciarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_CalculadoraEstandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_CalculadoraEstandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_CalculadoraEstandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_CalculadoraEstandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            //</editor-fold>
            //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_CalculadoraEstandar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCambiarSigno;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonNumero1;
    private javax.swing.JButton botonNumero2;
    private javax.swing.JButton botonNumero3;
    private javax.swing.JButton botonNumero4;
    private javax.swing.JButton botonNumero5;
    private javax.swing.JButton botonNumero6;
    private javax.swing.JButton botonNumero7;
    private javax.swing.JButton botonNumero8;
    private javax.swing.JButton botonNumero9;
    private javax.swing.JButton botonPuntoDecimal;
    private javax.swing.JToggleButton botonRaizCuadrada;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetaNumeros;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem menuCalculadoraEstandar;
    private javax.swing.JMenuItem menuConversorDivisas;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelCalculadora;
    private javax.swing.JPopupMenu.Separator separador1;
    // End of variables declaration//GEN-END:variables
}